name: Deploy DeCasimos to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: decasimos-grocery
        directory: ./
        wranglerVersion: '3'

    - name: Notify deployment success
      if: success()
      run: |
        echo "🎉 DeCasimos grocery website deployed successfully!"
        echo "🌐 Site should be live at: https://decasimos.pages.dev"

    - name: Notify deployment failure
      if: failure()
      run: |
        echo "❌ Deployment failed. Check the logs above for details."
